/* eslint-disable */
// This file is generated by webapp/scripts/generate-tooltip-content.mjs from TOOLTIPS.md.
// Do not edit this file directly.

export type TooltipBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }

export type LayoutOpenTooltipItem = {
  id: string
  title: string
  blocks: TooltipBlock[]
}

export const LAYOUT_OPEN_TOOLTIP_ITEMS = [
  {
    "id": "tooltip-start-with-system",
    "title": "Start With The Page System",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Set format, baseline, margins, grid, rhythm, type scale, and base font before placing many layers. If the page feels wrong, adjust the system first. Local paragraph fixes are most useful after the grid field is already stable."
      }
    ]
  },
  {
    "id": "tooltip-structure-before-styling",
    "title": "Structure Before Styling",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Rows`, `Baselines`, and `Cols` to define the text frame before refining wording, tracking, or color. The frame is the editorial decision. Styling should clarify that decision, not compensate for a weak one."
      }
    ]
  },
  {
    "id": "tooltip-repetitive-reference",
    "title": "Use Repetitive As A Control",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Start with `Repetitive` rhythm when judging a layout. It gives the clearest read on whether margins, baseline, and hierarchy are working. Move to Fibonacci, Golden Ratio, Perfect Fourth, or Perfect Fifth only when the structure benefits from asymmetry."
      }
    ]
  },
  {
    "id": "tooltip-create-text",
    "title": "Create Text Directly On The Grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click inside a module to create a paragraph exactly where the page structure suggests it belongs. The created block uses the clicked module, so deliberate clicks matter. Place first, refine second."
      }
    ]
  },
  {
    "id": "tooltip-create-hierarchy",
    "title": "Choose Hierarchy While Creating",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hold `1..6` while double-clicking to create a paragraph with the intended hierarchy immediately. Use `1 Caption`, `2 Body`, `3 Subhead`, `4 Headline`, `5 Custom`, and `6 Display`."
      }
    ]
  },
  {
    "id": "tooltip-create-image",
    "title": "Add Image Placeholders In Place",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Shift` + double-click on an empty module to create an image placeholder. Image placeholders share the same snap, span, baseline-height, and rotation discipline as text blocks, so they should be placed with the same structural care."
      }
    ]
  },
  {
    "id": "tooltip-lorem-frame-test",
    "title": "Use Lorem As A Frame Test",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Insert `<%lorem%>` when you need to test whether a paragraph frame can carry the intended text density. `<%lorem%>` fills the active frame using its current rows, baselines, columns, reflow, and hyphenation settings."
      }
    ]
  },
  {
    "id": "tooltip-drag-and-nudge",
    "title": "Drag For Placement, Nudge For Decision",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Drag to establish the rough position. Use cursor keys to make controlled placement decisions. Arrow-key nudging uses the same logical placement model as drag, so movement stays tied to the grid instead of becoming arbitrary screen motion."
      }
    ]
  },
  {
    "id": "tooltip-cursor-nudge",
    "title": "Nudge With The Grid",
    "blocks": [
      {
        "type": "paragraph",
        "text": "With snapped axes enabled, arrow keys move the selected unlocked layer by columns and module rows. Hold `Shift` while nudging to switch snapped Y movement to baseline rows. On unsnapped axes, `Shift` increases the fine movement step."
      }
    ]
  },
  {
    "id": "tooltip-duplicate-layer",
    "title": "Duplicate Without Losing Rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Alt/Option` + drag to duplicate a paragraph or image placeholder. Hovered text paragraphs also expose a `+` affordance: click copies the full paragraph, `Shift` + click copies `Paragraph` settings, `Alt/Option` + click copies `Typo` settings, and `Alt/Option` + `Shift` + click copies both for transfer onto another paragraph, even across pages and loaded layouts."
      }
    ]
  },
  {
    "id": "tooltip-free-placement",
    "title": "Free Placement Is An Exception",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Turn off `Snap to Columns (X)` or `Snap to Baseline (Y)` only when the composition needs a controlled exception. Free X placement allows a disciplined one-column side-margin overhang. It is useful for optical tension, not casual alignment drift."
      }
    ]
  },
  {
    "id": "tooltip-smart-text-zoom",
    "title": "Smart Text Zoom Keeps The Work Local",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Keep Smart Text Zoom on when editing text-heavy layouts. Entering text edit focuses the active paragraph. Ordinary text and style edits keep the current view stable, while frame-geometry changes refit the paragraph."
      }
    ]
  },
  {
    "id": "tooltip-turbo-edit",
    "title": "Turbo Edit Paragraph To Paragraph",
    "blocks": [
      {
        "type": "paragraph",
        "text": "When an editor is open, click another unlocked preview paragraph to retarget the editor immediately. Use this to move through a page paragraph by paragraph without repeatedly closing and reopening edit mode."
      }
    ]
  },
  {
    "id": "tooltip-layer-card-retarget",
    "title": "Turbo Edit From Layer Cards",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Double-click an unlocked layer card in the Project panel to open or retarget the corresponding text or image editor. Single-click still only selects the layer, which keeps keyboard nudging available without accidentally entering edit mode."
      }
    ]
  },
  {
    "id": "tooltip-rendered-text-editing",
    "title": "Edit The Rendered Text, Not A Generic Textarea",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Inside inline text edit, cursor movement follows the rendered line layout. Double-click selects a word, triple-click selects a sentence, and `Alt+A` or `Cmd/Ctrl+A` selects the whole paragraph."
      }
    ]
  },
  {
    "id": "tooltip-placeholder-editing",
    "title": "Keep Placeholders Visible While Editing",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Document variables stay visible as raw tokens while editing, then render as live values outside edit mode. Use this to place folios, project titles, dates, times, and proof text with predictable editorial control."
      }
    ]
  },
  {
    "id": "tooltip-rows-plus-baselines",
    "title": "Frame Height Is Rows Plus Baselines",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Paragraph and image heights are built from `rows + baselines`. Use full rows for modular blocks and baseline-only height for shallow editorial frames, captions, folios, and proof lines."
      }
    ]
  },
  {
    "id": "tooltip-columns-before-reflow",
    "title": "Set Columns Before Reflow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Choose `Cols` before judging paragraph flow. A weak line length is usually a frame problem. Reflow and hyphenation work best after the column span is structurally correct."
      }
    ]
  },
  {
    "id": "tooltip-frame-alignment",
    "title": "Align Inside The Frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Horizontal and vertical alignment position text inside the configured paragraph frame. Use alignment to make a compositional decision within a clear frame, not to repair a poorly placed frame."
      }
    ]
  },
  {
    "id": "tooltip-custom-type",
    "title": "Use Custom Type Deliberately",
    "blocks": [
      {
        "type": "paragraph",
        "text": "When first selected, `Custom` copies the paragraph's resolved size and leading. Treat Custom as a local editorial exception after the hierarchy is clear."
      }
    ]
  },
  {
    "id": "tooltip-select-before-nudge",
    "title": "Select Before Nudging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Single-click a layer card to select it, then use arrow keys to nudge it. This keeps placement changes precise and avoids entering edit mode when you only need a positional adjustment."
      }
    ]
  },
  {
    "id": "tooltip-lock-finished-layers",
    "title": "Lock Finished Layers",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Lock layers once their position and role are resolved. Locked layers stay visible but cannot be hovered, moved, edited, or retargeted until unlocked, which protects stable structure during later edits."
      }
    ]
  },
  {
    "id": "tooltip-page-cards",
    "title": "Use Page Cards For Document Rhythm",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use page cards to activate, rename, reorder, and inspect pages. Page order is part of the design. Treat it with the same discipline as grid and type hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-facing-pages",
    "title": "Use Facing Pages Only For Real Spreads",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `Facing pages` when two physical pages need one continuous editorial field. A facing spread remains one project page, doubles the effective column field, mirrors inner and outer margins, and affects physical page variables."
      }
    ]
  },
  {
    "id": "tooltip-preview-guides",
    "title": "Toggle Guides While Judging",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use the header toggles to inspect baselines, margins, modules, typography, and image placeholders. Judge the same layout both with and without guides. A strong layout should keep its rhythm after the construction lines disappear."
      }
    ]
  },
  {
    "id": "tooltip-rollover-guides",
    "title": "Rollover Guides Show The Frame",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Hover a layer to see its edit access and placement guides. Paragraph guides follow the configured `rows + baselines` frame, not only the visible text bounds."
      }
    ]
  },
  {
    "id": "tooltip-help-hover",
    "title": "Help Hover Is Contextual",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Open Help, then hover blue-marked UI areas to jump the Help panel to the matching reference. This works for header actions, settings sections, the preview surface, editor sections, and the preset browser."
      }
    ]
  },
  {
    "id": "tooltip-export-readiness",
    "title": "Export Only After The System Is Stable",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export should confirm a resolved layout, not repair it. Before exporting, check page order, page range, visible guide toggles, rotation, page numbering, and document variables."
      }
    ]
  },
  {
    "id": "tooltip-export-format",
    "title": "Pick Export By Downstream Use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use `PDF` for faithful vector output, `SVG` for frozen per-page vector geometry, and `IDML` for InDesign continuation. SVG and IDML freeze typography as geometry, so choose them when exact shape fidelity matters more than live text editing."
      }
    ]
  },
  {
    "id": "tooltip-export-visibility",
    "title": "WYSIWYG Includes The Visible Overlays",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Export follows the current preview visibility state for baselines, margins, modules, typography, and image placeholders. Turn off construction guides before final output unless they are intentionally part of the deliverable."
      }
    ]
  },
  {
    "id": "tooltip-fix-loose-page",
    "title": "If The Page Feels Loose",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Return to baseline, margins, and grid rhythm before editing individual paragraphs. Most loose layouts need a clearer field, not more local styling."
      }
    ]
  },
  {
    "id": "tooltip-fix-weak-type",
    "title": "If Text Feels Weak",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Check hierarchy, frame width, leading, and baseline alignment before changing tracking. Tracking changes the color of the paragraph. It should refine type texture, not replace hierarchy."
      }
    ]
  },
  {
    "id": "tooltip-grid-reduction",
    "title": "If Content Falls Out Of Bounds",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Grid reductions are blocked when existing layers would fall outside the new field. Resolve the layer placement first, then reduce rows or columns. The tool protects composition by refusing silent repositioning."
      }
    ]
  },
  {
    "id": "tooltip-faster-editing",
    "title": "If Editing Feels Slow",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Use Smart Text Zoom, open one editor, then retarget from paragraph to paragraph or layer card to layer card. The fastest workflow is not many commands. It is staying in context while moving through the page deliberately."
      }
    ]
  }
] as const satisfies readonly LayoutOpenTooltipItem[]
