/* eslint-disable */
// This file is generated by webapp/scripts/generate-help-content.mjs from HELP.md.
// Do not edit this file directly.

export type HelpDirectiveName = "AVAILABLE_FONTS" | "SHORTCUT_TABLE" | "DOCUMENT_VARIABLE_TOKENS"

export type HelpBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "directive"; name: HelpDirectiveName }

export type HelpSubsection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
}

export type HelpSection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
  subsections: HelpSubsection[]
}

export type HelpGroup = {
  title: string
  sections: HelpSection[]
}

export const HELP_CONTENT_GROUPS = [
  {
    "title": "Quick Start",
    "sections": [
      {
        "title": "Quick Start",
        "id": "help-quick-start",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set ratio, orientation, and rotation in `I. Canvas Ratio`.",
              "Set the baseline first. It drives everything.",
              "Set margins in `III. Margins`.",
              "Set columns, rows, gutter, and rhythm in `IV. Grid & Rhythms`.",
              "Set the type scale and base font in `V. Typo & Rhythms`.",
              "Use the header toggles to inspect baselines, margins, modules, and type."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "General Guidance",
    "sections": [
      {
        "title": "General Guidance",
        "id": "help-general-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Core editing and layout workflows."
          }
        ],
        "subsections": []
      },
      {
        "title": "Preview Workspace",
        "id": "help-preview-workspace",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The preview is the live layout surface for the active page.",
              "Double-click inside a module to add text. `Shift` + double-click adds an image placeholder.",
              "Hold `1..6` while double-clicking empty space to choose the new paragraph hierarchy: `1 Caption`, `2 Body`, `3 Subhead`, `4 Headline`, `5 Custom`, `6 Display`.",
              "Hover a layer to reveal edit access and placement guides.",
              "Drag to move. `Alt/Option` + drag duplicates.",
              "Hovered text paragraphs expose a `+` affordance: click to copy the full paragraph, `Shift` + click to copy `Paragraph` settings, `Alt/Option` + click to copy `Typo` settings, and `Alt/Option` + `Shift` + click to copy both. Then click another paragraph to apply the copied content/settings, even on a different page or after loading another layout.",
              "Preview visibility toggles control whether baselines, margins, modules, typography, and image placeholders are shown on the active page.",
              "Locked layers stay visible but cannot be hovered, moved, or edited until unlocked in the Project panel.",
              "Arrow keys nudge the selected unlocked layer. Snapped axes move by the grid; unsnapped axes move in fine steps. `Shift` increases the unsnapped step and switches snapped Y to baseline movement.",
              "`Page Up`, `Page Down`, `Home`, and `End` navigate project pages.",
              "Undo/redo includes placement, duplication, deletion, and editor changes."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Text Editor",
        "id": "help-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open text edit from the preview affordance, or by double-clicking an unlocked text layer card in the Project panel.",
              "Retarget an open text editor by clicking another unlocked preview block or by double-clicking another unlocked text layer card in the Project panel.",
              "While editing, the left sidebar switches to `Paragraph`, `Typo`, `Symbols`, `Placeholders`, and `Info`.",
              "Those editor sections remember their last open/closed GUI state and panel scroll position across pages and paragraphs inside the current document. First use starts with all sections closed, and opening another document or preset resets the editor panels to the closed, top-aligned state.",
              "The editor title uses the same layer label shown in the Project panel.",
              "`Esc` or outside click exits edit mode.",
              "Inside inline text edit: double-click selects a word, triple-click selects a sentence, `Alt+A` or `Cmd/Ctrl+A` selects all, and `Arrow` / `Home` / `End` follow the rendered line layout."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Paragraph Section",
            "id": "help-editor-paragraph",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, alignment, reflow, hyphenation, X/Y snap, and rotation.",
                  "Height is `rows + baselines`.",
                  "`Rows` may be `0` when `Baselines` is greater than `0`, so shallow editorial frames stay possible.",
                  "`Rows`, `Baselines`, and `Cols` preview on dropdown hover before commit.",
                  "`Snap to Columns (X)` locks to columns. Off allows free horizontal placement with controlled side overhang.",
                  "`Snap to Baseline (Y)` locks to the editorial Y system. Off allows free vertical placement."
                ]
              }
            ]
          },
          {
            "title": "Typo Section",
            "id": "help-editor-typo",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set font family, cut, hierarchy, color, kerning, tracking, and `Custom` size/leading.",
                  "Choosing `Custom` seeds the size and leading fields from the paragraph's current resolved metrics.",
                  "If text is selected, type and color controls apply to the selection instead of the whole paragraph.",
                  "Font, cut, hierarchy, and scheme preview on dropdown hover before commit."
                ]
              }
            ]
          },
          {
            "title": "Symbols Section",
            "id": "help-editor-symbols",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert typographic symbols at the caret or over the current selection.",
                  "Symbol insertion stores normal paragraph text plus a run-level `Noto Sans Symbols 2` font assignment for stable canvas and export rendering.",
                  "Recent symbols appear above the grouped palette after first use."
                ]
              }
            ]
          },
          {
            "title": "Placeholders Section",
            "id": "help-editor-placeholders",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert document-variable tokens at the caret or over the current selection.",
                  "`<%lorem%>` fills the active frame using its current geometry and reflow settings.",
                  "`<%page%>` and `<%pages%>` use physical page counts. On facing spreads, the right side resolves to the next physical page number.",
                  "Available tokens: {{DOCUMENT_VARIABLE_TOKENS}}."
                ]
              }
            ]
          },
          {
            "title": "Info Section",
            "id": "help-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Shows geometry, type summary, counts, and `Max/Line`."
                ]
              }
            ]
          }
        ]
      },
      {
        "title": "Image Editor",
        "id": "help-image-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "`Shift` + double-click on an empty space in the preview to create a new image placeholder.",
              "Open from the preview affordance or by double-clicking the corresponding unlocked image layer card in the Project panel.",
              "The left sidebar switches to `Geometry`, `Color`, and `Info`.",
              "Those editor sections remember their last open/closed GUI state and panel scroll position across pages and image placeholders inside the current document. First use starts with all sections closed, and opening another document or preset resets the editor panels to the closed, top-aligned state.",
              "The editor title shows `IMAGE` plus the current placeholder swatch color.",
              "`Esc` or outside click exits edit mode.",
              "Double-clicking another unlocked active-page image layer card retargets the open image editor."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Geometry Section",
            "id": "help-image-editor-geometry",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, X/Y snap, and rotation.",
                  "Height is `rows + baselines`.",
                  "`Rows`, `Baselines`, and `Cols` preview on dropdown hover before commit."
                ]
              }
            ]
          },
          {
            "title": "Color Section",
            "id": "help-image-editor-color",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set scheme, swatch color, and transparency."
                ]
              }
            ]
          },
          {
            "title": "Info Section",
            "id": "help-image-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Shows the current geometry, snap state, rotation, scheme, color, and transparency."
                ]
              }
            ]
          }
        ]
      },
      {
        "title": "Drag and Placement",
        "id": "help-drag-placement",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Drag respects each layer's current X/Y snap settings.",
              "With `Snap to Baseline (Y)` on, normal drag uses module tops.",
              "Holding `Shift` during drag switches Y movement to baseline rows.",
              "Unsnapped layers still stay inside their allowed placement bounds.",
              "With `Snap to Columns (X)` off, paragraphs and image placeholders may overhang by one column into the side margins.",
              "Selected layers can also be moved via cursor keys `UP`, `DOWN`, `LEFT`, `RIGHT`. `SHIFT` + `Cursor Keys` increments the steps 10x."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "History and Reflow",
        "id": "help-history-reflow",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Undo/redo covers settings, content edits, and placement changes.",
              "Reducing rows or columns never auto-repositions existing layers.",
              "If a grid reduction would push content out of bounds, the change is blocked and a warning is shown."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Save and Load Project JSON",
        "id": "help-save-load",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Save stores project metadata, pages, page settings, layout state, and optional tours.",
              "`Save to Library` opens a metadata dialog for project title plus optional description and author, then stores the full project in the local `Users` library as a gzip-compressed archive.",
              "`Import` restores the full project and active page from either a saved project JSON or a compressed `.swissgridgenerator` archive.",
              "Legacy single-page JSON is still accepted and wrapped into a one-page project.",
              "Positioned layers are stored with logical anchors so layouts stay stable across grid changes.",
              "Supabase email-code auth is optional and used only for cloud sync."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-export",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Export supports JSON, vector PDF, SVG, and IDML.",
              "Multi-page projects can export a page range.",
              "The dialog includes format switcher, page-range selectors, filename field, and export progress.",
              "Exports are WYSIWYG with respect to the current preview visibility state for baselines, margins, modules, typography, and image placeholders.",
              "PDF, SVG, and IDML exports are 100% vector based.",
              "JSON exports the full editable project document with metadata, pages, and current layout state, with an optional gzip-compressed `.swissgridgenerator` variant.",
              "PDF exports store available project metadata in the PDF document info dictionary.",
              "SVG exports embed available project metadata in the SVG metadata block.",
              "IDML exports carry project metadata into the package XMP metadata.",
              "PDF includes print presets plus optional bleed and registration-style marks.",
              "Multi-page SVG exports a ZIP with one outlined SVG per selected page.",
              "IDML exports separate guides, typography, and placeholder layers with frozen text geometry.",
              "`Esc` closes the dialog when no export is running and cancels an in-progress export at the next safe checkpoint."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Project Tours",
        "id": "help-project-tours",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "A loaded project may include an optional guided tour overlay.",
              "Closed tours can be reopened from the `Open Tour` button at the bottom of the preview.",
              "Tour steps can move between pages, highlight layers, open editors, jump to help topics, or wait for a specific layer click before advancing."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Layout Tooltips",
        "id": "help-layout-tooltips",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Loading a preset or project also opens a short workflow tooltip at the bottom of the preview.",
              "The popup fades in, shows one authored tip at a time, and stays open until it is closed with `X`, outside click, or replaced with `Next >`.",
              "`Next >` cycles through the tooltip sequence and updates the `Tooltip x of y` counter.",
              "When Help is open, the tooltip popup becomes an orange-marked help target like the rest of the interface and hovering it jumps the Help panel to this section."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Application Controls",
    "sections": [
      {
        "title": "UX Reference",
        "id": "help-ux-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Global controls and panel behavior."
          }
        ],
        "subsections": []
      },
      {
        "title": "Application Controls",
        "id": "help-application-controls-overview",
        "indexed": false,
        "blocks": [],
        "subsections": []
      },
      {
        "title": "Header and Sidebars",
        "id": "help-sidebars-header",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Header actions cover presets, import, save, export, undo/redo, dark mode, smart text zoom, display toggles, Project, help, and cloud account.",
              "The Project panel can be toggled with `Cmd/Ctrl+Shift+P`.",
              "`Shift` + click on a page-visibility toggle applies the same state to every page in the project."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Help Navigation",
        "id": "help-help-navigation",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "When help is open, orange-marked UI targets jump to their matching help topic on hover.",
              "Opening the Help panel also enables those contextual help markers across header actions, settings panels, the preview surface, and the preset browser.",
              "The layout-tooltip popup uses the same help-hover logic and only shows its orange top indicator while Help is open.",
              "The Help panel remains available while the preset browser is open.",
              "While the preset browser is open and the left settings controls are inactive, the left-panel section headers still keep their help-hover targets.",
              "Use the small up-arrow beside a help title to jump back to the index."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Presets",
        "id": "help-header-examples",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens the presets browser.",
              "Bundled files are grouped into `1. Presets` and `2. Examples`. `3. Users` is reserved for user files.",
              "With rollover info enabled, hovering a preset thumbnail shows title, description, author, and date metadata.",
              "User thumbnails in `3. Users` show the orange status dot while the local copy is not yet fully cloud-synced.",
              "Deleting a user thumbnail removes it locally immediately and, when required, queues or performs a Supabase soft-delete for the cloud copy.",
              "Double-click a thumbnail to load it.",
              "`Esc` closes the browser without loading.",
              "Shortcut: `Cmd/Ctrl+Shift+4`."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Import",
        "id": "help-header-load",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Imports a saved project JSON or compressed `.swissgridgenerator` archive. Shortcut: `Cmd/Ctrl+O`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Save",
        "id": "help-header-save",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Opens the `Save to Library` dialog for project title, description, and author, then stores the current project in the local `Users` library as a gzip-compressed archive. Shortcut: `Cmd/Ctrl+S`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Cloud Account",
        "id": "help-cloud-account",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The header account icon opens the right sidebar cloud account panel.",
              "The account icon shows a green status dot only when the user is signed in and cloud sync is fully up to date; otherwise it stays orange.",
              "While signed out, the `STATUS` row reads `Not connected`.",
              "Magic-link sign-in uses Supabase browser auth.",
              "Signed-in projects continue to use Dexie as the offline cache while syncing to Supabase in the background.",
              "Existing saved user-library projects auto-save locally and sync debounced to the cloud while you edit.",
              "Auth and cloud-sync failures are translated into user-facing messages for rate limits, permissions, offline state, session expiry, and setup errors.",
              "When the tab is hidden or closed, the app performs a best-effort local autosave flush and a best-effort cloud sync for already-saved user-library projects."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-header-export",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Opens export for JSON, PDF, SVG, and IDML. Shortcut: `Cmd/Ctrl+Shift+E`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Undo",
        "id": "help-header-undo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reverts the latest history step. Shortcut: `Cmd/Ctrl+Z`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Redo",
        "id": "help-header-redo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reapplies an undone history step. Shortcut: `Cmd/Ctrl+Shift+Z` or `Cmd/Ctrl+Y`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Dark Mode",
        "id": "help-header-dark-mode",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles light and dark UI themes. Shortcut: `Cmd/Ctrl+Shift+D`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Smart Text Zoom",
        "id": "help-header-smart-text-zoom",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles automatic zoom-to-paragraph while text editing. When enabled, entering text edit zooms to the active paragraph, ordinary text/style edits keep the current zoom, geometry changes (`Rows`, `Baselines`, `Cols`) refit it, and leaving text edit returns to full-page fit."
          }
        ],
        "subsections": []
      },
      {
        "title": "Baselines Toggle",
        "id": "help-header-baselines",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides baseline guides on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+B`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Margins Toggle",
        "id": "help-header-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides margin guides on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+M`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Modules Toggle",
        "id": "help-header-modules",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides modules and gutters on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+G`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Typography Toggle",
        "id": "help-header-typography",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides typography overlays on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+T`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Image Placeholders Toggle",
        "id": "help-header-image-placeholders",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides image placeholders on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+J`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Project Panel",
        "id": "help-header-layers",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens the project title and page/layer management panel.",
              "The small `i` toggle in the Project header shows or hides the document info text.",
              "The `TITLE` section keeps the compact title row visible by default and can be expanded to show `Description` and `Author`.",
              "The document info text summarizes pages, layers, fonts, cuts, words, characters, author, and creation date when metadata exists.",
              "Single-click a page card to activate it. Double-click it to open or close its inline layer list.",
              "Drag collapsed page cards to reorder the project.",
              "Page cards include rename and delete controls. The last remaining page cannot be deleted.",
              "`Facing pages` converts a page into a spread inside the same page record.",
              "`Add Page` always creates a new single page, even if the active page is a facing spread.",
              "A project can contain up to `1000` pages.",
              "Active-page layer cards mirror preview hover/guides.",
              "Drag unlocked layer cards to reorder z-index.",
              "Layer cards include lock and delete controls.",
              "Single-click a layer card to select it. Double-click an unlocked layer card to open or retarget its corresponding text or image editor.",
              "Double-click a layer card's lock toggle to apply the same lock state to every layer on that page.",
              "Locked layers stay visible and selectable, but preview hover, move, and editor access are disabled until unlocked."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Feedback",
        "id": "help-feedback-panel",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The footer `Feedback` action opens a structured survey sidebar.",
              "It collects experience level, workflow feedback, bugs, missing features, improvement ideas, and optional email.",
              "Submitting feedback posts the form to the configured feedback backend."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Imprint",
        "id": "help-imprint-panel",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The footer `Imprint` action opens the app imprint sidebar.",
              "It shows app, developer, license, contact, and the short Swiss-design disclaimer text."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Keyboard Shortcuts",
        "id": "help-shortcuts",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "`Cmd/Ctrl` means `Cmd` on macOS and `Ctrl` on Windows/Linux."
          },
          {
            "type": "directive",
            "name": "SHORTCUT_TABLE"
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Grid Generator Settings",
    "sections": [
      {
        "title": "Grid Generator Settings",
        "id": "help-grid-generator-settings-overview",
        "indexed": false,
        "blocks": [],
        "subsections": []
      },
      {
        "title": "I. Canvas Ratio & Rotation",
        "id": "help-canvas-ratio",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Choose a preset ratio or enter `Custom Ratio`.",
              "`Custom Ratio` accepts fractional width/height values and also accepts decimal comma input.",
              "`Ratio` and `Orientation` preview on dropdown hover before commit.",
              "Rotation turns the full preview/export composition."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "II. Baseline Grid",
        "id": "help-baseline-grid",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The baseline controls vertical rhythm for the grid and type.",
              "Available baseline options run from `6pt` to `72pt` and are filtered so the current page still keeps a usable number of lines.",
              "Top and bottom margins stay baseline-aligned."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "III. Margins",
        "id": "help-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Choose a margin method or `Custom Margins`.",
              "Margin method previews on dropdown hover before commit.",
              "`Baseline Multiple` scales the margin system while keeping baseline alignment.",
              "`Custom Margins` exposes top, left, right, and bottom baseline-multiplier controls."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "IV. Grid & Rhythms",
        "id": "help-gutter",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set columns, rows, gutter, and rhythm.",
              "Rhythm options preview on dropdown hover before commit.",
              "Non-repetitive rhythms can be enabled and directed independently for rows and columns.",
              "Reducing rows or columns is blocked when existing content would fall outside the new grid."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "V. Typo & Rhythms",
        "id": "help-typo",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set the type scale and base font for the document.",
              "`Rhythm` and `Base` preview on dropdown hover before commit.",
              "In the settings sidebar, dropdowns open upward.",
              "The `Steps` table shows the resolved size/leading values for `Display`, `Headline`, `Subhead`, `Body`, and `Caption` on the active baseline.",
              "Blocks without explicit overrides inherit the base font."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "VI. Available Fonts",
        "id": "help-available-fonts",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Base-font and paragraph font pickers use the same grouped family list.",
              "Font-family pickers preview hovered families live before commit.",
              "Each listed family links to its Google Fonts specimen page."
            ]
          },
          {
            "type": "directive",
            "name": "AVAILABLE_FONTS"
          }
        ],
        "subsections": []
      },
      {
        "title": "VII. Color Scheme",
        "id": "help-color-scheme",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Sets the base scheme for new image placeholders.",
              "`Background` applies `None` or a scheme color to the page.",
              "The same scheme system is used in the image editor, where individual placeholders can still override swatch color and transparency.",
              "Scheme and background preview on dropdown hover before commit."
            ]
          }
        ],
        "subsections": []
      }
    ]
  }
] as const satisfies readonly HelpGroup[]

export const HELP_INDEX_GROUPS = [
  {
    "title": "Quick Start",
    "items": [
      {
        "id": "help-quick-start",
        "label": "Quick Start"
      }
    ]
  },
  {
    "title": "General Guidance",
    "items": [
      {
        "id": "help-preview-workspace",
        "label": "Preview Workspace"
      },
      {
        "id": "help-editor",
        "label": "Text Editor"
      },
      {
        "id": "help-image-editor",
        "label": "Image Editor"
      },
      {
        "id": "help-drag-placement",
        "label": "Drag and Placement"
      },
      {
        "id": "help-history-reflow",
        "label": "History and Reflow"
      },
      {
        "id": "help-save-load",
        "label": "Save and Load Project JSON"
      },
      {
        "id": "help-export",
        "label": "Export"
      },
      {
        "id": "help-project-tours",
        "label": "Project Tours"
      },
      {
        "id": "help-layout-tooltips",
        "label": "Layout Tooltips"
      }
    ]
  },
  {
    "title": "Application Controls",
    "items": [
      {
        "id": "help-sidebars-header",
        "label": "Header and Sidebars"
      },
      {
        "id": "help-help-navigation",
        "label": "Help Navigation"
      },
      {
        "id": "help-header-examples",
        "label": "Presets"
      },
      {
        "id": "help-header-load",
        "label": "Import"
      },
      {
        "id": "help-header-save",
        "label": "Save"
      },
      {
        "id": "help-cloud-account",
        "label": "Cloud Account"
      },
      {
        "id": "help-header-export",
        "label": "Export"
      },
      {
        "id": "help-header-undo",
        "label": "Undo"
      },
      {
        "id": "help-header-redo",
        "label": "Redo"
      },
      {
        "id": "help-header-dark-mode",
        "label": "Dark Mode"
      },
      {
        "id": "help-header-smart-text-zoom",
        "label": "Smart Text Zoom"
      },
      {
        "id": "help-header-baselines",
        "label": "Baselines Toggle"
      },
      {
        "id": "help-header-margins",
        "label": "Margins Toggle"
      },
      {
        "id": "help-header-modules",
        "label": "Modules Toggle"
      },
      {
        "id": "help-header-typography",
        "label": "Typography Toggle"
      },
      {
        "id": "help-header-image-placeholders",
        "label": "Image Placeholders Toggle"
      },
      {
        "id": "help-header-layers",
        "label": "Project Panel"
      },
      {
        "id": "help-feedback-panel",
        "label": "Feedback"
      },
      {
        "id": "help-imprint-panel",
        "label": "Imprint"
      },
      {
        "id": "help-shortcuts",
        "label": "Keyboard Shortcuts"
      }
    ]
  },
  {
    "title": "Grid Generator Settings",
    "items": [
      {
        "id": "help-canvas-ratio",
        "label": "I. Canvas Ratio & Rotation"
      },
      {
        "id": "help-baseline-grid",
        "label": "II. Baseline Grid"
      },
      {
        "id": "help-margins",
        "label": "III. Margins"
      },
      {
        "id": "help-gutter",
        "label": "IV. Grid & Rhythms"
      },
      {
        "id": "help-typo",
        "label": "V. Typo & Rhythms"
      },
      {
        "id": "help-available-fonts",
        "label": "VI. Available Fonts"
      },
      {
        "id": "help-color-scheme",
        "label": "VII. Color Scheme"
      }
    ]
  }
] as const

export const ALL_HELP_INDEX_ITEMS = [
  {
    "id": "help-quick-start",
    "label": "Quick Start"
  },
  {
    "id": "help-general-overview",
    "label": "General Guidance"
  },
  {
    "id": "help-preview-workspace",
    "label": "Preview Workspace"
  },
  {
    "id": "help-editor",
    "label": "Text Editor"
  },
  {
    "id": "help-image-editor",
    "label": "Image Editor"
  },
  {
    "id": "help-drag-placement",
    "label": "Drag and Placement"
  },
  {
    "id": "help-history-reflow",
    "label": "History and Reflow"
  },
  {
    "id": "help-save-load",
    "label": "Save and Load Project JSON"
  },
  {
    "id": "help-export",
    "label": "Export"
  },
  {
    "id": "help-project-tours",
    "label": "Project Tours"
  },
  {
    "id": "help-layout-tooltips",
    "label": "Layout Tooltips"
  },
  {
    "id": "help-ux-overview",
    "label": "UX Reference"
  },
  {
    "id": "help-application-controls-overview",
    "label": "Application Controls"
  },
  {
    "id": "help-sidebars-header",
    "label": "Header and Sidebars"
  },
  {
    "id": "help-help-navigation",
    "label": "Help Navigation"
  },
  {
    "id": "help-header-examples",
    "label": "Presets"
  },
  {
    "id": "help-header-load",
    "label": "Import"
  },
  {
    "id": "help-header-save",
    "label": "Save"
  },
  {
    "id": "help-cloud-account",
    "label": "Cloud Account"
  },
  {
    "id": "help-header-export",
    "label": "Export"
  },
  {
    "id": "help-header-undo",
    "label": "Undo"
  },
  {
    "id": "help-header-redo",
    "label": "Redo"
  },
  {
    "id": "help-header-dark-mode",
    "label": "Dark Mode"
  },
  {
    "id": "help-header-smart-text-zoom",
    "label": "Smart Text Zoom"
  },
  {
    "id": "help-header-baselines",
    "label": "Baselines Toggle"
  },
  {
    "id": "help-header-margins",
    "label": "Margins Toggle"
  },
  {
    "id": "help-header-modules",
    "label": "Modules Toggle"
  },
  {
    "id": "help-header-typography",
    "label": "Typography Toggle"
  },
  {
    "id": "help-header-image-placeholders",
    "label": "Image Placeholders Toggle"
  },
  {
    "id": "help-header-layers",
    "label": "Project Panel"
  },
  {
    "id": "help-feedback-panel",
    "label": "Feedback"
  },
  {
    "id": "help-imprint-panel",
    "label": "Imprint"
  },
  {
    "id": "help-shortcuts",
    "label": "Keyboard Shortcuts"
  },
  {
    "id": "help-grid-generator-settings-overview",
    "label": "Grid Generator Settings"
  },
  {
    "id": "help-canvas-ratio",
    "label": "I. Canvas Ratio & Rotation"
  },
  {
    "id": "help-baseline-grid",
    "label": "II. Baseline Grid"
  },
  {
    "id": "help-margins",
    "label": "III. Margins"
  },
  {
    "id": "help-gutter",
    "label": "IV. Grid & Rhythms"
  },
  {
    "id": "help-typo",
    "label": "V. Typo & Rhythms"
  },
  {
    "id": "help-available-fonts",
    "label": "VI. Available Fonts"
  },
  {
    "id": "help-color-scheme",
    "label": "VII. Color Scheme"
  }
] as const

export const EDITOR_HELP_SUBSECTION_ITEMS = [
  {
    "id": "help-editor-paragraph",
    "label": "Text Editor / Paragraph"
  },
  {
    "id": "help-editor-typo",
    "label": "Text Editor / Typo"
  },
  {
    "id": "help-editor-symbols",
    "label": "Text Editor / Symbols"
  },
  {
    "id": "help-editor-placeholders",
    "label": "Text Editor / Placeholders"
  },
  {
    "id": "help-editor-info",
    "label": "Text Editor / Info"
  },
  {
    "id": "help-image-editor-geometry",
    "label": "Image Editor / Geometry"
  },
  {
    "id": "help-image-editor-color",
    "label": "Image Editor / Color"
  },
  {
    "id": "help-image-editor-info",
    "label": "Image Editor / Info"
  }
] as const

export const ALL_HELP_SECTION_ITEMS = [
  ...ALL_HELP_INDEX_ITEMS,
  ...EDITOR_HELP_SUBSECTION_ITEMS,
] as const

export type HelpSectionId = (typeof ALL_HELP_SECTION_ITEMS)[number]["id"]
