/* eslint-disable */
// This file is generated by webapp/scripts/generate-help-content.mjs from HELP.md.
// Do not edit this file directly.

export type HelpDirectiveName = "AVAILABLE_FONTS" | "SHORTCUT_TABLE" | "DOCUMENT_VARIABLE_TOKENS"

export type HelpBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "directive"; name: HelpDirectiveName }

export type HelpSubsection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
}

export type HelpSection = {
  id: string
  title: string
  indexed: boolean
  blocks: HelpBlock[]
  subsections: HelpSubsection[]
}

export type HelpGroup = {
  title: string
  sections: HelpSection[]
}

export const HELP_CONTENT_GROUPS = [
  {
    "title": "Quick Start",
    "sections": [
      {
        "title": "Quick Start",
        "id": "help-quick-start",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set ratio, orientation, and rotation in `I. Canvas Ratio`.",
              "Set the baseline first. It drives vertical rhythm.",
              "Set margins in `III. Margins`.",
              "Set columns, rows, gutter, and rhythm in `IV. Grid & Rhythms`.",
              "Set the type scale and base font in `V. Typo`.",
              "Use the header toggles to inspect baselines, margins, modules, and type."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "General Guidance",
    "sections": [
      {
        "title": "General Guidance",
        "id": "help-general-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Core editing and layout workflows."
          }
        ],
        "subsections": []
      },
      {
        "title": "Preview Workspace",
        "id": "help-preview-workspace",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The preview is the live layout surface for the active page.",
              "Double-click empty space to add text. `Shift` + double-click adds an image placeholder.",
              "Hover a layer to reveal edit access and placement guides.",
              "Drag to move. `Alt/Option` + drag duplicates.",
              "Locked layers stay visible but cannot be hovered, moved, or edited until unlocked in the Project panel.",
              "Arrow keys nudge the selected unlocked layer. Snapped axes move by the grid; unsnapped axes move in fine steps. `Shift` increases the unsnapped step and switches snapped Y to baseline movement.",
              "`Page Up`, `Page Down`, `Home`, and `End` navigate project pages.",
              "Undo/redo includes placement, duplication, deletion, and editor changes."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Text Editor",
        "id": "help-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open text edit from the preview affordance, or retarget an open editor by clicking another unlocked preview block.",
              "While editing, the left sidebar switches to `Paragraph`, `Typo`, `Placeholders`, and `Info`.",
              "`Esc` or outside click exits edit mode.",
              "Inside inline text edit: double-click selects a word, triple-click selects a sentence, `Alt+A` or `Cmd/Ctrl+A` selects all, and `Arrow` / `Home` / `End` follow the rendered line layout."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Paragraph Section",
            "id": "help-editor-paragraph",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, alignment, reflow, hyphenation, X/Y snap, and rotation.",
                  "Height is `rows + baselines`.",
                  "`Rows`, `Baselines`, and `Cols` preview on dropdown hover before commit.",
                  "`Snap to Columns (X)` locks to columns. Off allows free horizontal placement with controlled side overhang.",
                  "`Snap to Baseline (Y)` locks to the editorial Y system. Off allows free vertical placement."
                ]
              }
            ]
          },
          {
            "title": "Typo Section",
            "id": "help-editor-typo",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set font family, cut, hierarchy, color, kerning, tracking, and `Custom` size/leading.",
                  "If text is selected, type and color controls apply to the selection instead of the whole paragraph.",
                  "Font, cut, hierarchy, and scheme preview on dropdown hover before commit."
                ]
              }
            ]
          },
          {
            "title": "Placeholders Section",
            "id": "help-editor-placeholders",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Insert document-variable tokens at the caret or over the current selection.",
                  "`<%lorem%>` fills the active frame using its current geometry and reflow settings.",
                  "Available tokens: {{DOCUMENT_VARIABLE_TOKENS}}."
                ]
              }
            ]
          },
          {
            "title": "Info Section",
            "id": "help-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Shows geometry, type summary, counts, and `Max/Line`."
                ]
              }
            ]
          }
        ]
      },
      {
        "title": "Image Editor",
        "id": "help-image-editor",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open from the preview affordance or by `Shift` + double-clicking empty space.",
              "The left sidebar switches to `Geometry`, `Color`, and `Info`.",
              "`Esc` or outside click exits edit mode.",
              "Double-clicking another active-page layer card retargets the open image editor."
            ]
          }
        ],
        "subsections": [
          {
            "title": "Geometry Section",
            "id": "help-image-editor-geometry",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set rows, baselines, columns, X/Y snap, and rotation.",
                  "Height is `rows + baselines`.",
                  "`Rows`, `Baselines`, and `Cols` preview on dropdown hover before commit."
                ]
              }
            ]
          },
          {
            "title": "Color Section",
            "id": "help-image-editor-color",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Set scheme, swatch color, and transparency."
                ]
              }
            ]
          },
          {
            "title": "Info Section",
            "id": "help-image-editor-info",
            "indexed": true,
            "blocks": [
              {
                "type": "list",
                "items": [
                  "Shows the current geometry, snap state, rotation, scheme, color, and transparency."
                ]
              }
            ]
          }
        ]
      },
      {
        "title": "Drag and Placement",
        "id": "help-drag-placement",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Drag respects each layer's current X/Y snap settings.",
              "With `Snap to Baseline (Y)` on, normal drag uses module tops.",
              "Holding `Shift` during drag switches Y movement to baseline rows.",
              "Unsnapped layers still stay inside their allowed placement bounds."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "History and Reflow",
        "id": "help-history-reflow",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Undo/redo covers settings, content edits, and placement changes.",
              "Reducing rows or columns never auto-repositions existing layers.",
              "If a grid reduction would push content out of bounds, the change is blocked and a warning is shown."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Save and Load Project JSON",
        "id": "help-save-load",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Save stores project metadata, pages, page settings, layout state, and optional tours.",
              "Load restores the full project and active page.",
              "Legacy single-page JSON is still accepted and wrapped into a one-page project.",
              "Positioned layers are stored with logical anchors so layouts stay stable across grid changes."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-export",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Export supports vector PDF, SVG, and IDML.",
              "Multi-page projects can export a page range.",
              "PDF stays visually faithful. SVG and IDML are the frozen-geometry path when you do not want live text."
            ]
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Application Controls",
    "sections": [
      {
        "title": "UX Reference",
        "id": "help-ux-overview",
        "indexed": false,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Global controls and panel behavior."
          }
        ],
        "subsections": []
      },
      {
        "title": "Application Controls",
        "id": "help-application-controls-overview",
        "indexed": false,
        "blocks": [],
        "subsections": []
      },
      {
        "title": "Header and Sidebars",
        "id": "help-sidebars-header",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Header actions cover presets, load, save, export, undo/redo, dark mode, smart text zoom, display toggles, Project, and help.",
              "`Save`, `Export`, and display toggles stay disabled until a preview layout exists.",
              "The Project panel can also be toggled with `Cmd/Ctrl+Shift+P`.",
              "Header icon labels are always available as hover popups.",
              "`Shift` + click on a page-visibility toggle applies the same state to every page in the project.",
              "In settings dropdowns, hover previews stay local. Hold `Shift` while committing a value to apply the committed choice to all pages.",
              "Only one right-side panel is open at a time."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Help Navigation",
        "id": "help-help-navigation",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Open help from the header.",
              "When help is open, blue-marked UI targets jump to their matching help topic on hover.",
              "Use the small up-arrow beside a help title to jump back to the index."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Presets",
        "id": "help-header-examples",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens the presets browser.",
              "Bundled files are grouped into `1. Presets` and `2. Examples`. `3. Users` is reserved for user files.",
              "Double-click a thumbnail to load it.",
              "`Esc` closes the browser without loading.",
              "Shortcut: `Cmd/Ctrl+Shift+4`."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Load",
        "id": "help-header-load",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Loads a saved project JSON. Shortcut: `Cmd/Ctrl+O`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Save",
        "id": "help-header-save",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Saves the current project JSON. Shortcut: `Cmd/Ctrl+S`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Export",
        "id": "help-header-export",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Opens export for PDF, SVG, and IDML. Shortcut: `Cmd/Ctrl+Shift+E`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Undo",
        "id": "help-header-undo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reverts the latest history step. Shortcut: `Cmd/Ctrl+Z`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Redo",
        "id": "help-header-redo",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Reapplies an undone history step. Shortcut: `Cmd/Ctrl+Shift+Z` or `Cmd/Ctrl+Y`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Dark Mode",
        "id": "help-header-dark-mode",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles light and dark UI themes. Shortcut: `Cmd/Ctrl+Shift+D`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Smart Text Zoom",
        "id": "help-header-smart-text-zoom",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Toggles automatic zoom-to-paragraph while text editing."
          }
        ],
        "subsections": []
      },
      {
        "title": "Baselines Toggle",
        "id": "help-header-baselines",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides baseline guides on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+B`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Margins Toggle",
        "id": "help-header-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides margin guides on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+M`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Modules Toggle",
        "id": "help-header-modules",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides modules and gutters on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+G`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Typography Toggle",
        "id": "help-header-typography",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides typography overlays on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+T`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Image Placeholders Toggle",
        "id": "help-header-image-placeholders",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "Shows or hides image placeholders on the active page. `Shift` + click applies the same state to all pages. Shortcut: `Cmd/Ctrl+Shift+J`."
          }
        ],
        "subsections": []
      },
      {
        "title": "Project Panel",
        "id": "help-header-layers",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Opens the project title and page/layer management panel.",
              "Single-click a page card to activate it. Double-click it to open or close its inline layer list.",
              "`Facing pages` converts a page into a spread inside the same page record.",
              "Active-page layer cards mirror preview hover/guides.",
              "Drag unlocked layer cards to reorder z-index.",
              "Single-click a layer card to select it. Double-click it to open or retarget the editor.",
              "Locked layers stay visible and selectable, but preview hover, move, and editor access are disabled until unlocked."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "Keyboard Shortcuts",
        "id": "help-shortcuts",
        "indexed": true,
        "blocks": [
          {
            "type": "paragraph",
            "text": "`Cmd/Ctrl` means `Cmd` on macOS and `Ctrl` on Windows/Linux."
          },
          {
            "type": "directive",
            "name": "SHORTCUT_TABLE"
          }
        ],
        "subsections": []
      }
    ]
  },
  {
    "title": "Grid Generator Settings",
    "sections": [
      {
        "title": "Grid Generator Settings",
        "id": "help-grid-generator-settings-overview",
        "indexed": false,
        "blocks": [],
        "subsections": []
      },
      {
        "title": "I. Canvas Ratio & Rotation",
        "id": "help-canvas-ratio",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Choose a preset ratio or enter `Custom Ratio`.",
              "`Ratio` and `Orientation` preview on dropdown hover before commit.",
              "Rotation turns the full preview/export composition."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "II. Baseline Grid",
        "id": "help-baseline-grid",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "The baseline controls vertical rhythm for the grid and type.",
              "Top and bottom margins stay baseline-aligned."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "III. Margins",
        "id": "help-margins",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Choose a margin method or `Custom Margins`.",
              "Margin method previews on dropdown hover before commit.",
              "`Baseline Multiple` scales the margin system while keeping baseline alignment."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "IV. Grid & Rhythms",
        "id": "help-gutter",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set columns, rows, gutter, and rhythm.",
              "Rhythm options preview on dropdown hover before commit.",
              "Reducing rows or columns is blocked when existing content would fall outside the new grid."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "V. Typo",
        "id": "help-typo",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Set the type scale and base font for the document.",
              "`Font Hierarchy` and `Base Font` preview on dropdown hover before commit.",
              "Blocks without explicit overrides inherit the base font."
            ]
          }
        ],
        "subsections": []
      },
      {
        "title": "VI. Available Fonts",
        "id": "help-available-fonts",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Base-font and paragraph font pickers use the same grouped family list.",
              "Font-family pickers preview hovered families live before commit.",
              "Each listed family links to its Google Fonts specimen page."
            ]
          },
          {
            "type": "directive",
            "name": "AVAILABLE_FONTS"
          }
        ],
        "subsections": []
      },
      {
        "title": "VII. Color Scheme",
        "id": "help-color-scheme",
        "indexed": true,
        "blocks": [
          {
            "type": "list",
            "items": [
              "Sets the base scheme for new image placeholders.",
              "`Background` applies `None` or a scheme color to the page.",
              "Scheme and background preview on dropdown hover before commit."
            ]
          }
        ],
        "subsections": []
      }
    ]
  }
] as const satisfies readonly HelpGroup[]

export const HELP_INDEX_GROUPS = [
  {
    "title": "Quick Start",
    "items": [
      {
        "id": "help-quick-start",
        "label": "Quick Start"
      }
    ]
  },
  {
    "title": "General Guidance",
    "items": [
      {
        "id": "help-preview-workspace",
        "label": "Preview Workspace"
      },
      {
        "id": "help-editor",
        "label": "Text Editor"
      },
      {
        "id": "help-image-editor",
        "label": "Image Editor"
      },
      {
        "id": "help-drag-placement",
        "label": "Drag and Placement"
      },
      {
        "id": "help-history-reflow",
        "label": "History and Reflow"
      },
      {
        "id": "help-save-load",
        "label": "Save and Load Project JSON"
      },
      {
        "id": "help-export",
        "label": "Export"
      }
    ]
  },
  {
    "title": "Application Controls",
    "items": [
      {
        "id": "help-sidebars-header",
        "label": "Header and Sidebars"
      },
      {
        "id": "help-help-navigation",
        "label": "Help Navigation"
      },
      {
        "id": "help-header-examples",
        "label": "Presets"
      },
      {
        "id": "help-header-load",
        "label": "Load"
      },
      {
        "id": "help-header-save",
        "label": "Save"
      },
      {
        "id": "help-header-export",
        "label": "Export"
      },
      {
        "id": "help-header-undo",
        "label": "Undo"
      },
      {
        "id": "help-header-redo",
        "label": "Redo"
      },
      {
        "id": "help-header-dark-mode",
        "label": "Dark Mode"
      },
      {
        "id": "help-header-smart-text-zoom",
        "label": "Smart Text Zoom"
      },
      {
        "id": "help-header-baselines",
        "label": "Baselines Toggle"
      },
      {
        "id": "help-header-margins",
        "label": "Margins Toggle"
      },
      {
        "id": "help-header-modules",
        "label": "Modules Toggle"
      },
      {
        "id": "help-header-typography",
        "label": "Typography Toggle"
      },
      {
        "id": "help-header-image-placeholders",
        "label": "Image Placeholders Toggle"
      },
      {
        "id": "help-header-layers",
        "label": "Project Panel"
      },
      {
        "id": "help-shortcuts",
        "label": "Keyboard Shortcuts"
      }
    ]
  },
  {
    "title": "Grid Generator Settings",
    "items": [
      {
        "id": "help-canvas-ratio",
        "label": "I. Canvas Ratio & Rotation"
      },
      {
        "id": "help-baseline-grid",
        "label": "II. Baseline Grid"
      },
      {
        "id": "help-margins",
        "label": "III. Margins"
      },
      {
        "id": "help-gutter",
        "label": "IV. Grid & Rhythms"
      },
      {
        "id": "help-typo",
        "label": "V. Typo"
      },
      {
        "id": "help-available-fonts",
        "label": "VI. Available Fonts"
      },
      {
        "id": "help-color-scheme",
        "label": "VII. Color Scheme"
      }
    ]
  }
] as const

export const ALL_HELP_INDEX_ITEMS = [
  {
    "id": "help-quick-start",
    "label": "Quick Start"
  },
  {
    "id": "help-general-overview",
    "label": "General Guidance"
  },
  {
    "id": "help-preview-workspace",
    "label": "Preview Workspace"
  },
  {
    "id": "help-editor",
    "label": "Text Editor"
  },
  {
    "id": "help-image-editor",
    "label": "Image Editor"
  },
  {
    "id": "help-drag-placement",
    "label": "Drag and Placement"
  },
  {
    "id": "help-history-reflow",
    "label": "History and Reflow"
  },
  {
    "id": "help-save-load",
    "label": "Save and Load Project JSON"
  },
  {
    "id": "help-export",
    "label": "Export"
  },
  {
    "id": "help-ux-overview",
    "label": "UX Reference"
  },
  {
    "id": "help-application-controls-overview",
    "label": "Application Controls"
  },
  {
    "id": "help-sidebars-header",
    "label": "Header and Sidebars"
  },
  {
    "id": "help-help-navigation",
    "label": "Help Navigation"
  },
  {
    "id": "help-header-examples",
    "label": "Presets"
  },
  {
    "id": "help-header-load",
    "label": "Load"
  },
  {
    "id": "help-header-save",
    "label": "Save"
  },
  {
    "id": "help-header-export",
    "label": "Export"
  },
  {
    "id": "help-header-undo",
    "label": "Undo"
  },
  {
    "id": "help-header-redo",
    "label": "Redo"
  },
  {
    "id": "help-header-dark-mode",
    "label": "Dark Mode"
  },
  {
    "id": "help-header-smart-text-zoom",
    "label": "Smart Text Zoom"
  },
  {
    "id": "help-header-baselines",
    "label": "Baselines Toggle"
  },
  {
    "id": "help-header-margins",
    "label": "Margins Toggle"
  },
  {
    "id": "help-header-modules",
    "label": "Modules Toggle"
  },
  {
    "id": "help-header-typography",
    "label": "Typography Toggle"
  },
  {
    "id": "help-header-image-placeholders",
    "label": "Image Placeholders Toggle"
  },
  {
    "id": "help-header-layers",
    "label": "Project Panel"
  },
  {
    "id": "help-shortcuts",
    "label": "Keyboard Shortcuts"
  },
  {
    "id": "help-grid-generator-settings-overview",
    "label": "Grid Generator Settings"
  },
  {
    "id": "help-canvas-ratio",
    "label": "I. Canvas Ratio & Rotation"
  },
  {
    "id": "help-baseline-grid",
    "label": "II. Baseline Grid"
  },
  {
    "id": "help-margins",
    "label": "III. Margins"
  },
  {
    "id": "help-gutter",
    "label": "IV. Grid & Rhythms"
  },
  {
    "id": "help-typo",
    "label": "V. Typo"
  },
  {
    "id": "help-available-fonts",
    "label": "VI. Available Fonts"
  },
  {
    "id": "help-color-scheme",
    "label": "VII. Color Scheme"
  }
] as const

export const EDITOR_HELP_SUBSECTION_ITEMS = [
  {
    "id": "help-editor-paragraph",
    "label": "Text Editor / Paragraph"
  },
  {
    "id": "help-editor-typo",
    "label": "Text Editor / Typo"
  },
  {
    "id": "help-editor-placeholders",
    "label": "Text Editor / Placeholders"
  },
  {
    "id": "help-editor-info",
    "label": "Text Editor / Info"
  },
  {
    "id": "help-image-editor-geometry",
    "label": "Image Editor / Geometry"
  },
  {
    "id": "help-image-editor-color",
    "label": "Image Editor / Color"
  },
  {
    "id": "help-image-editor-info",
    "label": "Image Editor / Info"
  }
] as const

export const ALL_HELP_SECTION_ITEMS = [
  ...ALL_HELP_INDEX_ITEMS,
  ...EDITOR_HELP_SUBSECTION_ITEMS,
] as const

export type HelpSectionId = (typeof ALL_HELP_SECTION_ITEMS)[number]["id"]
