export const PREVIEW_LAYOUT_CHANGE_DEBOUNCE_MS = 120
export const PREVIEW_TOUCH_LONG_PRESS_MS = 180
export const PREVIEW_TOUCH_CANCEL_DISTANCE_PX = 10
export const PREVIEW_DRAG_CLICK_GUARD_MS = 250
export const PREVIEW_DRAG_MOVE_THRESHOLD_PX = 3
export const PREVIEW_LAYER_SELECTION_GRACE_MS = 300
