// This file is auto-generated by scripts/generate-preset-manifest.mjs.
// Do not edit it manually.

export const GENERATED_PRESET_MANIFEST = [
  {
    path: "./data/4x4 12pt grid with image placeholder.json",
    source: {
      "schemaVersion": 2,
      "exportedAt": "2026-04-02T10:28:01.844Z",
      "title": "4x4 12pt grid with image placeholder.",
      "description": "",
      "author": "netzwerkerei@gmail.com",
      "createdAt": "2026-03-16T14:40:58.992Z",
      "activePageId": "page-b28b5ad2-6c39-4e4e-9a95-a79cfdefe8ce",
      "pages": [
        {
          "id": "page-b28b5ad2-6c39-4e4e-9a95-a79cfdefe8ce",
          "name": "Page 1",
          "uiSettings": {
            "canvasRatio": "din_ab",
            "orientation": "portrait",
            "rotation": 0,
            "marginMethod": 3,
            "gridCols": 3,
            "gridRows": 4,
            "baselineMultiple": 1,
            "gutterMultiple": 1,
            "rhythm": "repetitive",
            "rhythmRowsEnabled": true,
            "rhythmRowsDirection": "ltr",
            "rhythmColsEnabled": true,
            "rhythmColsDirection": "ttb",
            "typographyScale": "swiss",
            "baseFont": "Inter",
            "imageColorScheme": "mono",
            "canvasBackground": "#404040",
            "customBaseline": 12,
            "useCustomMargins": true,
            "customMarginMultipliers": {
              "top": 3,
              "left": 4,
              "right": 4,
              "bottom": 2
            },
            "showBaselines": true,
            "showModules": true,
            "showMargins": true,
            "showImagePlaceholders": true,
            "showTypography": true,
            "showLayers": true,
            "collapsed": {
              "format": true,
              "baseline": true,
              "margins": false,
              "gutter": false,
              "typo": true,
              "color": false,
              "summary": true
            },
            "exportPaperSize": "A4",
            "exportPrintPro": false,
            "exportBleedMm": 0,
            "exportRegistrationMarks": false,
            "displayUnit": "pt",
            "format": "A4"
          },
          "previewLayout": {
            "blockOrder": [
              "display",
              "paragraph-1773671347303-6ze5tl",
              "paragraph-1773671562475-vr75kg",
              "paragraph-1773671586677-x9575v",
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab",
              "paragraph-1773671949302-15nbra"
            ],
            "textContent": {
              "display": "m",
              "paragraph-1773671347303-6ze5tl": "Swiss Grid System",
              "paragraph-1773671562475-vr75kg": "Oper von Luigi Cherubini Erstaufführung in italienischer SpracheSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671586677-x9575v": "Oper von Luigi Cherubini Erstaufführung in italienischer Sprache\nSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671949302-15nbra": "Swiss Grid Generator, 2026",
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": "Oper von Luigi Cherubini Erstaufführung in italienischer Sprache\nSamstag, 19. Februar 1972 20 Uhr"
            },
            "blockTextEdited": {
              "display": true,
              "paragraph-1773671347303-6ze5tl": true,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-1773671949302-15nbra": true,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": true
            },
            "styleAssignments": {
              "display": "fx",
              "paragraph-1773671347303-6ze5tl": "fx",
              "paragraph-1773671562475-vr75kg": "body",
              "paragraph-1773671586677-x9575v": "body",
              "paragraph-1773671949302-15nbra": "caption",
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": "body"
            },
            "blockFontFamilies": {
              "display": "Playfair Display"
            },
            "blockFontWeights": {
              "display": 700,
              "paragraph-1773671347303-6ze5tl": 400,
              "paragraph-1773671562475-vr75kg": 400,
              "paragraph-1773671586677-x9575v": 400,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": 400,
              "paragraph-1773671949302-15nbra": 400
            },
            "blockOpticalKerning": {
              "display": true,
              "paragraph-1773671347303-6ze5tl": true,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": true,
              "paragraph-1773671949302-15nbra": true
            },
            "blockTrackingScales": {
              "display": 0,
              "paragraph-1773671347303-6ze5tl": 0,
              "paragraph-1773671562475-vr75kg": 0,
              "paragraph-1773671586677-x9575v": 0,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": 0,
              "paragraph-1773671949302-15nbra": 0
            },
            "blockColumnSpans": {
              "display": 1,
              "paragraph-1773671347303-6ze5tl": 1,
              "paragraph-1773671562475-vr75kg": 1,
              "paragraph-1773671586677-x9575v": 1,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": 1,
              "paragraph-1773671949302-15nbra": 1
            },
            "blockRowSpans": {
              "display": 1,
              "paragraph-1773671347303-6ze5tl": 1,
              "paragraph-1773671562475-vr75kg": 1,
              "paragraph-1773671586677-x9575v": 1,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": 1,
              "paragraph-1773671949302-15nbra": 1
            },
            "blockTextAlignments": {
              "display": "left",
              "paragraph-1773671347303-6ze5tl": "left",
              "paragraph-1773671562475-vr75kg": "left",
              "paragraph-1773671586677-x9575v": "left",
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": "left",
              "paragraph-1773671949302-15nbra": "left"
            },
            "blockTextReflow": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockSyllableDivision": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": true,
              "paragraph-1773671949302-15nbra": true
            },
            "blockItalic": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockRotations": {
              "display": 0,
              "paragraph-1773671347303-6ze5tl": 0,
              "paragraph-1773671562475-vr75kg": 0,
              "paragraph-1773671586677-x9575v": 0,
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": 0,
              "paragraph-1773671949302-15nbra": 0
            },
            "blockModulePositions": {
              "display": {
                "column": 0,
                "row": 2,
                "baselineOffset": 4
              },
              "paragraph-1773671347303-6ze5tl": {
                "column": 0,
                "row": 0,
                "baselineOffset": 0
              },
              "paragraph-1773671562475-vr75kg": {
                "column": 0,
                "row": 2,
                "baselineOffset": 0
              },
              "paragraph-1773671586677-x9575v": {
                "column": 2,
                "row": 2,
                "baselineOffset": 0
              },
              "paragraph-1773671949302-15nbra": {
                "column": 0,
                "row": 3,
                "baselineOffset": 14
              },
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": {
                "column": 1,
                "row": 2,
                "baselineOffset": 0
              }
            },
            "blockCustomSizes": {
              "display": 400,
              "paragraph-1773671347303-6ze5tl": 96
            },
            "blockCustomLeadings": {
              "display": 106,
              "paragraph-1773671347303-6ze5tl": 84
            },
            "blockTextColors": {
              "display": "#ffffff",
              "paragraph-1773671347303-6ze5tl": "#c0c0c0",
              "paragraph-1773671562475-vr75kg": "#ffffff",
              "paragraph-1773671586677-x9575v": "#ffffff",
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab": "#ffffff",
              "paragraph-1773671949302-15nbra": "#ffffff"
            },
            "layerOrder": [
              "display",
              "paragraph-1773671347303-6ze5tl",
              "paragraph-1773671949302-15nbra",
              "paragraph-1773671562475-vr75kg",
              "paragraph-1773671586677-x9575v",
              "paragraph-77d427de-8908-4c40-8779-51724b9573ab"
            ],
            "imageOrder": [],
            "imageModulePositions": {},
            "imageColumnSpans": {},
            "imageRowSpans": {},
            "imageColors": {}
          }
        },
        {
          "id": "page-c2429484-17b9-4995-b78b-31a19fdebe59",
          "name": "Page 2",
          "uiSettings": {
            "canvasRatio": "din_ab",
            "orientation": "portrait",
            "rotation": 0,
            "marginMethod": 3,
            "gridCols": 3,
            "gridRows": 4,
            "baselineMultiple": 1,
            "gutterMultiple": 1,
            "rhythm": "repetitive",
            "rhythmRowsEnabled": true,
            "rhythmRowsDirection": "ltr",
            "rhythmColsEnabled": true,
            "rhythmColsDirection": "ttb",
            "typographyScale": "swiss",
            "baseFont": "Inter",
            "imageColorScheme": "mono",
            "canvasBackground": "#404040",
            "customBaseline": 12,
            "useCustomMargins": true,
            "customMarginMultipliers": {
              "top": 3,
              "left": 4,
              "right": 4,
              "bottom": 2
            },
            "showBaselines": true,
            "showModules": true,
            "showMargins": true,
            "showImagePlaceholders": true,
            "showTypography": true,
            "showLayers": true,
            "collapsed": {
              "format": true,
              "baseline": true,
              "margins": false,
              "gutter": false,
              "typo": true,
              "color": false,
              "summary": true
            },
            "exportPaperSize": "A4",
            "exportPrintPro": false,
            "exportBleedMm": 0,
            "exportRegistrationMarks": false,
            "displayUnit": "pt",
            "format": "A4"
          },
          "previewLayout": {
            "blockOrder": [
              "display",
              "paragraph-1773671347303-6ze5tl",
              "paragraph-1773671562475-vr75kg",
              "paragraph-1773671585233-cpbkzw",
              "paragraph-1773671586677-x9575v",
              "paragraph-1773671949302-15nbra"
            ],
            "textContent": {
              "display": "m",
              "paragraph-1773671347303-6ze5tl": "Swiss Grid System",
              "paragraph-1773671562475-vr75kg": "Oper von Luigi Cherubini Erstaufführung in italienischer SpracheSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671585233-cpbkzw": "Oper von Luigi Cherubini\nErstaufführung in italienischer SprachSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671586677-x9575v": "Oper von Luigi Cherubini Erstaufführung in italienischer Sprache\nSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671949302-15nbra": "Swiss Grid Generator, 2026"
            },
            "blockTextEdited": {
              "display": true,
              "paragraph-1773671347303-6ze5tl": true,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671585233-cpbkzw": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-1773671949302-15nbra": true
            },
            "styleAssignments": {
              "display": "fx",
              "paragraph-1773671347303-6ze5tl": "fx",
              "paragraph-1773671562475-vr75kg": "body",
              "paragraph-1773671585233-cpbkzw": "body",
              "paragraph-1773671586677-x9575v": "body",
              "paragraph-1773671949302-15nbra": "caption"
            },
            "blockFontFamilies": {
              "display": "Playfair Display"
            },
            "blockFontWeights": {
              "display": 700,
              "paragraph-1773671347303-6ze5tl": 400,
              "paragraph-1773671562475-vr75kg": 400,
              "paragraph-1773671585233-cpbkzw": 400,
              "paragraph-1773671586677-x9575v": 400,
              "paragraph-1773671949302-15nbra": 400
            },
            "blockOpticalKerning": {
              "display": true,
              "paragraph-1773671347303-6ze5tl": true,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671585233-cpbkzw": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-1773671949302-15nbra": true
            },
            "blockTrackingScales": {
              "display": 0,
              "paragraph-1773671347303-6ze5tl": 0,
              "paragraph-1773671562475-vr75kg": 0,
              "paragraph-1773671585233-cpbkzw": 0,
              "paragraph-1773671586677-x9575v": 0,
              "paragraph-1773671949302-15nbra": 0
            },
            "blockColumnSpans": {
              "display": 1,
              "paragraph-1773671347303-6ze5tl": 1,
              "paragraph-1773671562475-vr75kg": 1,
              "paragraph-1773671585233-cpbkzw": 1,
              "paragraph-1773671586677-x9575v": 1,
              "paragraph-1773671949302-15nbra": 1
            },
            "blockRowSpans": {
              "display": 1,
              "paragraph-1773671347303-6ze5tl": 1,
              "paragraph-1773671562475-vr75kg": 1,
              "paragraph-1773671585233-cpbkzw": 1,
              "paragraph-1773671586677-x9575v": 1,
              "paragraph-1773671949302-15nbra": 1
            },
            "blockTextAlignments": {
              "display": "left",
              "paragraph-1773671347303-6ze5tl": "left",
              "paragraph-1773671562475-vr75kg": "left",
              "paragraph-1773671585233-cpbkzw": "left",
              "paragraph-1773671586677-x9575v": "left",
              "paragraph-1773671949302-15nbra": "left"
            },
            "blockTextReflow": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671585233-cpbkzw": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockSyllableDivision": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671585233-cpbkzw": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-1773671949302-15nbra": true
            },
            "blockItalic": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671585233-cpbkzw": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockRotations": {
              "display": 0,
              "paragraph-1773671347303-6ze5tl": 0,
              "paragraph-1773671562475-vr75kg": 0,
              "paragraph-1773671585233-cpbkzw": 0,
              "paragraph-1773671586677-x9575v": 0,
              "paragraph-1773671949302-15nbra": 0
            },
            "blockModulePositions": {
              "display": {
                "column": 0,
                "row": 2,
                "baselineOffset": 4
              },
              "paragraph-1773671347303-6ze5tl": {
                "column": 0,
                "row": 0,
                "baselineOffset": 0
              },
              "paragraph-1773671562475-vr75kg": {
                "column": 0,
                "row": 2,
                "baselineOffset": 0
              },
              "paragraph-1773671585233-cpbkzw": {
                "column": 1,
                "row": 2,
                "baselineOffset": 0
              },
              "paragraph-1773671586677-x9575v": {
                "column": 2,
                "row": 2,
                "baselineOffset": 0
              },
              "paragraph-1773671949302-15nbra": {
                "column": 0,
                "row": 3,
                "baselineOffset": 14
              }
            },
            "blockCustomSizes": {
              "display": 400,
              "paragraph-1773671347303-6ze5tl": 96
            },
            "blockCustomLeadings": {
              "display": 106,
              "paragraph-1773671347303-6ze5tl": 84
            },
            "blockTextColors": {
              "display": "#ffffff",
              "paragraph-1773671347303-6ze5tl": "#c0c0c0",
              "paragraph-1773671562475-vr75kg": "#ffffff",
              "paragraph-1773671585233-cpbkzw": "#ffffff",
              "paragraph-1773671586677-x9575v": "#ffffff",
              "paragraph-1773671949302-15nbra": "#ffffff"
            },
            "layerOrder": [
              "display",
              "paragraph-1773671347303-6ze5tl",
              "paragraph-1773671562475-vr75kg",
              "paragraph-1773671585233-cpbkzw",
              "paragraph-1773671586677-x9575v",
              "paragraph-1773671949302-15nbra"
            ],
            "imageOrder": [],
            "imageModulePositions": {},
            "imageColumnSpans": {},
            "imageRowSpans": {},
            "imageColors": {}
          }
        }
      ]
    },
  },
  {
    path: "./data/din_ab_portrait_4x4_method1_12.000pt_grid_002.json",
    source: {
      "schemaVersion": 1,
      "exportedAt": "2026-03-16T14:40:58.992Z",
      "title": "4x4 12pt grid with image placeholder.",
      "description": "",
      "author": "netzwerkerei@gmail.com",
      "gridResult": {
        "format": "A4",
        "settings": {
          "orientation": "portrait",
          "marginMethod": "Baseline (1:1:1:1)",
          "marginMethodId": 3,
          "gridCols": 3,
          "gridRows": 4,
          "baselineMultiple": 2,
          "customBaseline": 12,
          "rhythm": "repetitive",
          "rhythmRowsEnabled": true,
          "rhythmRowsDirection": "ltr",
          "rhythmColsEnabled": true,
          "rhythmColsDirection": "ttb"
        },
        "pageSizePt": {
          "width": 595.276,
          "height": 841.89
        },
        "grid": {
          "gridUnit": 12,
          "gridMarginHorizontal": 12,
          "gridMarginVertical": 12,
          "margins": {
            "top": 36,
            "bottom": 24,
            "left": 48,
            "right": 48
          },
          "gutter": 12,
          "scaleFactor": 1,
          "baselineUnitsPerCell": 16
        },
        "contentArea": {
          "width": 499.276,
          "height": 756
        },
        "module": {
          "width": 158.425,
          "height": 180,
          "aspectRatio": 0.88,
          "widths": [
            158.425,
            158.425,
            158.425
          ],
          "heights": [
            180,
            180,
            180,
            180
          ]
        },
        "typography": {
          "metadata": {
            "format": "A4",
            "unit": "pt",
            "baselineGrid": 12,
            "a4Baseline": 12,
            "scaleFactor": 1
          },
          "styles": {
            "fx": {
              "size": 96,
              "leading": 96,
              "weight": "Bold",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 8,
              "bodyLines": 8
            },
            "caption": {
              "size": 7,
              "leading": 8,
              "weight": "Regular",
              "blockItalic": true,
              "alignment": "Left",
              "baselineMultiplier": 0.6666666666666666,
              "bodyLines": 1
            },
            "body": {
              "size": 10,
              "leading": 12,
              "weight": "Regular",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 1,
              "bodyLines": 1
            },
            "subhead": {
              "size": 20,
              "leading": 24,
              "weight": "Regular",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 2,
              "bodyLines": 2
            },
            "headline": {
              "size": 30,
              "leading": 36,
              "weight": "Bold",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 3,
              "bodyLines": 3
            },
            "display": {
              "size": 64,
              "leading": 72,
              "weight": "Bold",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 6,
              "bodyLines": 6
            }
          }
        }
      },
      "activePageId": "page-din-ab-portrait-4x4-method1-12-000pt-grid-002",
      "pages": [
        {
          "id": "page-din-ab-portrait-4x4-method1-12-000pt-grid-002",
          "name": "Page 1",
          "uiSettings": {
            "canvasRatio": "din_ab",
            "orientation": "portrait",
            "rotation": 0,
            "marginMethod": 3,
            "gridCols": 3,
            "gridRows": 4,
            "baselineMultiple": 2,
            "gutterMultiple": 1,
            "rhythm": "repetitive",
            "rhythmRowsEnabled": true,
            "rhythmRowsDirection": "ltr",
            "rhythmColsEnabled": true,
            "rhythmColsDirection": "ttb",
            "typographyScale": "swiss",
            "baseFont": "Inter",
            "imageColorScheme": "mono",
            "canvasBackground": "#404040",
            "customBaseline": 12,
            "useCustomMargins": true,
            "customMarginMultipliers": {
              "top": 3,
              "left": 4,
              "right": 4,
              "bottom": 2
            },
            "showBaselines": false,
            "showModules": true,
            "showMargins": true,
            "showImagePlaceholders": true,
            "showTypography": true,
            "showLayers": true,
            "collapsed": {
              "format": true,
              "baseline": true,
              "margins": false,
              "gutter": false,
              "typo": true,
              "color": false,
              "summary": true
            },
            "exportPaperSize": "A4",
            "exportPrintPro": false,
            "exportBleedMm": 0,
            "exportRegistrationMarks": false,
            "displayUnit": "pt",
            "format": "A4"
          },
          "previewLayout": {
            "blockOrder": [
              "display",
              "paragraph-1773671347303-6ze5tl",
              "paragraph-1773671562475-vr75kg",
              "paragraph-1773671585233-cpbkzw",
              "paragraph-1773671586677-x9575v",
              "paragraph-1773671949302-15nbra"
            ],
            "textContent": {
              "display": "m",
              "paragraph-1773671347303-6ze5tl": "Swiss Grid System",
              "paragraph-1773671562475-vr75kg": "Oper von Luigi Cherubini Erstaufführung in italienischer SpracheSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671585233-cpbkzw": "Oper von Luigi Cherubini\nErstaufführung in italienischer SprachSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671586677-x9575v": "Oper von Luigi Cherubini Erstaufführung in italienischer Sprache\nSamstag, 19. Februar 1972 20 Uhr",
              "paragraph-1773671949302-15nbra": "Swiss Grid Designer"
            },
            "blockTextEdited": {
              "display": true,
              "paragraph-1773671347303-6ze5tl": true,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671585233-cpbkzw": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-1773671949302-15nbra": true
            },
            "styleAssignments": {
              "display": "fx",
              "paragraph-1773671347303-6ze5tl": "fx",
              "paragraph-1773671562475-vr75kg": "body",
              "paragraph-1773671585233-cpbkzw": "body",
              "paragraph-1773671586677-x9575v": "body",
              "paragraph-1773671949302-15nbra": "caption"
            },
            "blockFontFamilies": {},
            "blockColumnSpans": {
              "display": 1,
              "paragraph-1773671347303-6ze5tl": 3,
              "paragraph-1773671562475-vr75kg": 1,
              "paragraph-1773671585233-cpbkzw": 1,
              "paragraph-1773671586677-x9575v": 1,
              "paragraph-1773671949302-15nbra": 1
            },
            "blockRowSpans": {
              "display": 1,
              "paragraph-1773671347303-6ze5tl": 1,
              "paragraph-1773671562475-vr75kg": 1,
              "paragraph-1773671585233-cpbkzw": 1,
              "paragraph-1773671586677-x9575v": 1,
              "paragraph-1773671949302-15nbra": 1
            },
            "blockTextAlignments": {
              "display": "left",
              "paragraph-1773671347303-6ze5tl": "left",
              "paragraph-1773671562475-vr75kg": "left",
              "paragraph-1773671585233-cpbkzw": "left",
              "paragraph-1773671586677-x9575v": "left",
              "paragraph-1773671949302-15nbra": "left"
            },
            "blockTextReflow": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671585233-cpbkzw": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockSyllableDivision": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": true,
              "paragraph-1773671562475-vr75kg": true,
              "paragraph-1773671585233-cpbkzw": true,
              "paragraph-1773671586677-x9575v": true,
              "paragraph-1773671949302-15nbra": true
            },
            "blockBold": {
              "display": true,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671585233-cpbkzw": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockItalic": {
              "display": false,
              "paragraph-1773671347303-6ze5tl": false,
              "paragraph-1773671562475-vr75kg": false,
              "paragraph-1773671585233-cpbkzw": false,
              "paragraph-1773671586677-x9575v": false,
              "paragraph-1773671949302-15nbra": false
            },
            "blockRotations": {
              "display": 0,
              "paragraph-1773671347303-6ze5tl": 0,
              "paragraph-1773671562475-vr75kg": 0,
              "paragraph-1773671585233-cpbkzw": 0,
              "paragraph-1773671586677-x9575v": 0,
              "paragraph-1773671949302-15nbra": 0
            },
            "blockCustomSizes": {
              "display": 400,
              "paragraph-1773671347303-6ze5tl": 56
            },
            "blockCustomLeadings": {
              "display": 106,
              "paragraph-1773671347303-6ze5tl": 96
            },
            "blockTextColors": {
              "display": "#ffffff",
              "paragraph-1773671347303-6ze5tl": "#c0c0c0",
              "paragraph-1773671562475-vr75kg": "#ffffff",
              "paragraph-1773671585233-cpbkzw": "#ffffff",
              "paragraph-1773671586677-x9575v": "#ffffff",
              "paragraph-1773671949302-15nbra": "#ffffff"
            },
            "blockModulePositions": {
              "display": {
                "col": 0,
                "row": 34
              },
              "paragraph-1773671347303-6ze5tl": {
                "col": 0,
                "row": 0
              },
              "paragraph-1773671562475-vr75kg": {
                "col": 0,
                "row": 16
              },
              "paragraph-1773671585233-cpbkzw": {
                "col": 1,
                "row": 16
              },
              "paragraph-1773671586677-x9575v": {
                "col": 2,
                "row": 16
              },
              "paragraph-1773671949302-15nbra": {
                "col": 0,
                "row": 62
              }
            },
            "layerOrder": [
              "display",
              "paragraph-1773671347303-6ze5tl",
              "paragraph-1773671562475-vr75kg",
              "paragraph-1773671585233-cpbkzw",
              "paragraph-1773671586677-x9575v",
              "paragraph-1773671949302-15nbra"
            ],
            "imageOrder": [],
            "imageModulePositions": {},
            "imageColumnSpans": {},
            "imageRowSpans": {},
            "imageColors": {}
          }
        }
      ]
    },
  },
  {
    path: "./data/din_ab_portrait_4x4_method1_12.000pt_grid.json",
    source: {
      "schemaVersion": 1,
      "exportedAt": "2026-03-09T12:51:56.921Z",
      "title": "4x4 12pt grid with image placeholder.",
      "description": "",
      "author": "netzwerkerei@gmail.com",
      "gridResult": {
        "format": "A4",
        "settings": {
          "orientation": "portrait",
          "marginMethod": "Progressive (1:2:2:3)",
          "marginMethodId": 1,
          "gridCols": 4,
          "gridRows": 4,
          "baselineMultiple": 1,
          "customBaseline": 12,
          "rhythm": "repetitive",
          "rhythmRowsEnabled": true,
          "rhythmRowsDirection": "ltr",
          "rhythmColsEnabled": true,
          "rhythmColsDirection": "ttb"
        },
        "pageSizePt": {
          "width": 595.276,
          "height": 841.89
        },
        "grid": {
          "gridUnit": 12,
          "gridMarginHorizontal": 12,
          "gridMarginVertical": 12,
          "margins": {
            "top": 12,
            "bottom": 12,
            "left": 12,
            "right": 12
          },
          "gutter": 12,
          "scaleFactor": 1,
          "baselineUnitsPerCell": 17
        },
        "contentArea": {
          "width": 571.276,
          "height": 804
        },
        "module": {
          "width": 133.819,
          "height": 192,
          "aspectRatio": 0.697,
          "widths": [
            133.819,
            133.819,
            133.819,
            133.819
          ],
          "heights": [
            192,
            192,
            192,
            192
          ]
        },
        "typography": {
          "metadata": {
            "format": "A4",
            "unit": "pt",
            "baselineGrid": 12,
            "a4Baseline": 12,
            "scaleFactor": 1
          },
          "styles": {
            "fx": {
              "size": 96,
              "leading": 96,
              "weight": "Bold",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 8,
              "bodyLines": 8
            },
            "caption": {
              "size": 7,
              "leading": 8,
              "weight": "Regular",
              "blockItalic": true,
              "alignment": "Left",
              "baselineMultiplier": 0.6666666666666666,
              "bodyLines": 1
            },
            "body": {
              "size": 10,
              "leading": 12,
              "weight": "Regular",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 1,
              "bodyLines": 1
            },
            "subhead": {
              "size": 20,
              "leading": 24,
              "weight": "Regular",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 2,
              "bodyLines": 2
            },
            "headline": {
              "size": 30,
              "leading": 36,
              "weight": "Bold",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 3,
              "bodyLines": 3
            },
            "display": {
              "size": 64,
              "leading": 72,
              "weight": "Bold",
              "blockItalic": false,
              "alignment": "Left",
              "baselineMultiplier": 6,
              "bodyLines": 6
            }
          }
        }
      },
      "activePageId": "page-din-ab-portrait-4x4-method1-12-000pt-grid",
      "pages": [
        {
          "id": "page-din-ab-portrait-4x4-method1-12-000pt-grid",
          "name": "Page 1",
          "uiSettings": {
            "canvasRatio": "din_ab",
            "orientation": "portrait",
            "rotation": 0,
            "marginMethod": 1,
            "gridCols": 4,
            "gridRows": 4,
            "baselineMultiple": 1,
            "gutterMultiple": 1,
            "rhythm": "repetitive",
            "rhythmRowsEnabled": true,
            "rhythmRowsDirection": "ltr",
            "rhythmColsEnabled": true,
            "rhythmColsDirection": "ttb",
            "typographyScale": "swiss",
            "baseFont": "Inter",
            "imageColorScheme": "swiss-modern",
            "canvasBackground": "scheme:0",
            "customBaseline": 12,
            "useCustomMargins": true,
            "customMarginMultipliers": {
              "top": 1,
              "left": 1,
              "right": 1,
              "bottom": 1
            },
            "showBaselines": true,
            "showModules": true,
            "showMargins": true,
            "showImagePlaceholders": true,
            "showTypography": true,
            "showLayers": true,
            "collapsed": {
              "format": true,
              "baseline": true,
              "margins": true,
              "gutter": true,
              "typo": true,
              "color": true,
              "summary": true
            },
            "exportPaperSize": "A4",
            "exportPrintPro": false,
            "exportBleedMm": 0,
            "exportRegistrationMarks": false,
            "exportFinalSafeGuides": true,
            "displayUnit": "pt",
            "format": "A4"
          },
          "previewLayout": {
            "blockOrder": [
              "display",
              "headline",
              "paragraph-1772610247079-0uugg8",
              "paragraph-1772610667455-372iaj",
              "paragraph-1772610667455-aooo5z",
              "body",
              "paragraph-1772528695124-y56i9f"
            ],
            "textContent": {
              "display": "Swiss Style",
              "headline": "Swiss 'Style\nGrid System",
              "paragraph-1772610247079-0uugg8": "12 pt Baseline Grid",
              "paragraph-1772610667455-372iaj": "DIN Ratio\nPortrait",
              "paragraph-1772610667455-aooo5z": "Progressive Margin\n1:2:2:3",
              "body": "The modular grid allows designers to organize content hierarchically and rhythmically. All typography aligns to the baseline grid, ensuring harmony across the page. Modular proportions guide rhythm, contrast, and emphasis while preserving clarity across complex layouts. Structure becomes a tool for expression rather than a constraint, enabling flexible yet coherent systems.",
              "paragraph-1772528695124-y56i9f": "Graphic design today\nstill carries the imprint\nof the International Typographic Style."
            },
            "blockTextEdited": {
              "display": true,
              "headline": true,
              "paragraph-1772610247079-0uugg8": true,
              "paragraph-1772610667455-372iaj": true,
              "paragraph-1772610667455-aooo5z": true,
              "body": true,
              "paragraph-1772528695124-y56i9f": true
            },
            "styleAssignments": {
              "display": "fx",
              "headline": "body",
              "paragraph-1772610247079-0uugg8": "body",
              "paragraph-1772610667455-372iaj": "body",
              "paragraph-1772610667455-aooo5z": "body",
              "body": "body",
              "paragraph-1772528695124-y56i9f": "subhead"
            },
            "blockFontFamilies": {},
            "blockColumnSpans": {
              "display": 2,
              "headline": 1,
              "paragraph-1772610247079-0uugg8": 1,
              "paragraph-1772610667455-372iaj": 1,
              "paragraph-1772610667455-aooo5z": 1,
              "body": 1,
              "paragraph-1772528695124-y56i9f": 2
            },
            "blockRowSpans": {
              "display": 1,
              "headline": 1,
              "paragraph-1772610247079-0uugg8": 1,
              "paragraph-1772610667455-372iaj": 1,
              "paragraph-1772610667455-aooo5z": 1,
              "body": 1,
              "paragraph-1772528695124-y56i9f": 1
            },
            "blockTextAlignments": {
              "display": "left",
              "headline": "left",
              "paragraph-1772610247079-0uugg8": "left",
              "paragraph-1772610667455-372iaj": "left",
              "paragraph-1772610667455-aooo5z": "left",
              "body": "left",
              "paragraph-1772528695124-y56i9f": "left"
            },
            "blockTextReflow": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": false,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockSyllableDivision": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": true,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockBold": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": false,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockItalic": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": false,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockRotations": {
              "display": 0,
              "headline": 0,
              "paragraph-1772610247079-0uugg8": 0,
              "paragraph-1772610667455-372iaj": 0,
              "paragraph-1772610667455-aooo5z": 0,
              "body": 0,
              "paragraph-1772528695124-y56i9f": 0
            },
            "blockCustomSizes": {
              "display": 106
            },
            "blockCustomLeadings": {
              "display": 90
            },
            "blockTextColors": {
              "body": "#0b3536"
            },
            "blockModulePositions": {
              "display": {
                "col": 0,
                "row": 17
              },
              "headline": {
                "col": 0,
                "row": 0
              },
              "paragraph-1772610247079-0uugg8": {
                "col": 2,
                "row": 0
              },
              "paragraph-1772610667455-372iaj": {
                "col": 1,
                "row": 0
              },
              "paragraph-1772610667455-aooo5z": {
                "col": 3,
                "row": 0
              },
              "body": {
                "col": 3,
                "row": 51
              },
              "paragraph-1772528695124-y56i9f": {
                "col": 0,
                "row": 51
              }
            },
            "layerOrder": [
              "image-1772622609257-u7uqot",
              "image-1772784142956-s1tyrm",
              "body",
              "paragraph-1772528695124-y56i9f",
              "display",
              "paragraph-1772610667455-aooo5z",
              "paragraph-1772610247079-0uugg8",
              "paragraph-1772610667455-372iaj",
              "headline"
            ],
            "imageOrder": [
              "image-1772622609257-u7uqot",
              "image-1772784142956-s1tyrm"
            ],
            "imageModulePositions": {
              "image-1772622609257-u7uqot": {
                "col": 3,
                "row": 34
              },
              "image-1772784142956-s1tyrm": {
                "col": 2,
                "row": 17
              }
            },
            "imageColumnSpans": {
              "image-1772622609257-u7uqot": 1,
              "image-1772784142956-s1tyrm": 2
            },
            "imageRowSpans": {
              "image-1772622609257-u7uqot": 1,
              "image-1772784142956-s1tyrm": 1
            },
            "imageColors": {
              "image-1772622609257-u7uqot": "scheme:2",
              "image-1772784142956-s1tyrm": "scheme:1"
            }
          }
        }
      ]
    },
  },
  {
    path: "./data/Swiss Style Poster A0 001.json",
    source: {
      "schemaVersion": 2,
      "exportedAt": "2026-04-07T07:09:34.928Z",
      "title": "Swiss Style Poster A0 001",
      "description": "",
      "author": "netzwerkerei@gmail.com",
      "createdAt": "2026-03-09T12:51:56.921Z",
      "activePageId": "page-din-ab-portrait-4x4-method1-12-000pt-grid",
      "pages": [
        {
          "id": "page-din-ab-portrait-4x4-method1-12-000pt-grid",
          "name": "Swiss Style Poster",
          "uiSettings": {
            "canvasRatio": "din_ab",
            "customRatioWidth": 4,
            "customRatioHeight": 5,
            "orientation": "portrait",
            "rotation": 0,
            "marginMethod": 3,
            "gridCols": 4,
            "gridRows": 4,
            "baselineMultiple": 1,
            "gutterMultiple": 1,
            "rhythm": "repetitive",
            "rhythmRowsEnabled": true,
            "rhythmRowsDirection": "ltr",
            "rhythmColsEnabled": true,
            "rhythmColsDirection": "ttb",
            "typographyScale": "swiss",
            "baseFont": "Inter",
            "imageColorScheme": "swiss-modern",
            "canvasBackground": "scheme:0",
            "customBaseline": 12,
            "useCustomMargins": false,
            "customMarginMultipliers": {
              "top": 1,
              "left": 1,
              "right": 1,
              "bottom": 1
            },
            "showBaselines": false,
            "showModules": false,
            "showMargins": false,
            "showImagePlaceholders": false,
            "showTypography": true,
            "showLayers": true,
            "collapsed": {
              "format": true,
              "baseline": true,
              "margins": true,
              "gutter": true,
              "typo": true,
              "color": true,
              "summary": true
            },
            "exportPrintPro": false,
            "exportBleedMm": 0,
            "exportRegistrationMarks": false,
            "format": "A4"
          },
          "previewLayout": {
            "blockOrder": [
              "display",
              "headline",
              "paragraph-1772610247079-0uugg8",
              "paragraph-1772610667455-372iaj",
              "paragraph-1772610667455-aooo5z",
              "body",
              "paragraph-1772528695124-y56i9f"
            ],
            "textContent": {
              "display": "Swiss Style",
              "headline": "Swiss Style\nGrid System",
              "paragraph-1772610247079-0uugg8": "12-Pt Baseline Grid",
              "paragraph-1772610667455-372iaj": "DIN Ratio\nPortrait",
              "paragraph-1772610667455-aooo5z": "Baseline Margin\n1:1:1:1",
              "body": "The modular grid allows designers to organize content hierarchically and rhythmically. All typography aligns to the baseline grid, ensuring harmony across the page. Modular proportions guide rhythm, contrast, and emphasis while preserving clarity across complex layouts. Structure becomes a tool for expression rather than a constraint, enabling flexible yet coherent systems.",
              "paragraph-1772528695124-y56i9f": "Graphic design today\nstill carries the imprint\nof the International Typographic Style."
            },
            "blockTextEdited": {
              "display": true,
              "headline": true,
              "paragraph-1772610247079-0uugg8": true,
              "paragraph-1772610667455-372iaj": true,
              "paragraph-1772610667455-aooo5z": true,
              "body": true,
              "paragraph-1772528695124-y56i9f": true
            },
            "styleAssignments": {
              "display": "fx",
              "headline": "body",
              "paragraph-1772610247079-0uugg8": "body",
              "paragraph-1772610667455-372iaj": "body",
              "paragraph-1772610667455-aooo5z": "body",
              "body": "body",
              "paragraph-1772528695124-y56i9f": "subhead"
            },
            "blockFontFamilies": {},
            "blockFontWeights": {
              "display": 400,
              "headline": 400,
              "paragraph-1772610247079-0uugg8": 400,
              "paragraph-1772610667455-372iaj": 400,
              "paragraph-1772610667455-aooo5z": 400,
              "body": 400,
              "paragraph-1772528695124-y56i9f": 400
            },
            "blockOpticalKerning": {
              "display": true,
              "headline": true,
              "paragraph-1772610247079-0uugg8": true,
              "paragraph-1772610667455-372iaj": true,
              "paragraph-1772610667455-aooo5z": true,
              "body": true,
              "paragraph-1772528695124-y56i9f": true
            },
            "blockTrackingScales": {
              "display": 0,
              "headline": 0,
              "paragraph-1772610247079-0uugg8": 0,
              "paragraph-1772610667455-372iaj": 0,
              "paragraph-1772610667455-aooo5z": 0,
              "body": 0,
              "paragraph-1772528695124-y56i9f": 0
            },
            "blockTrackingRuns": {},
            "blockTextFormatRuns": {},
            "blockColumnSpans": {
              "display": 2,
              "headline": 1,
              "paragraph-1772610247079-0uugg8": 1,
              "paragraph-1772610667455-372iaj": 1,
              "paragraph-1772610667455-aooo5z": 1,
              "body": 1,
              "paragraph-1772528695124-y56i9f": 2
            },
            "blockRowSpans": {
              "display": 1,
              "headline": 1,
              "paragraph-1772610247079-0uugg8": 1,
              "paragraph-1772610667455-372iaj": 1,
              "paragraph-1772610667455-aooo5z": 1,
              "body": 1,
              "paragraph-1772528695124-y56i9f": 1
            },
            "blockTextAlignments": {
              "display": "left",
              "headline": "left",
              "paragraph-1772610247079-0uugg8": "left",
              "paragraph-1772610667455-372iaj": "left",
              "paragraph-1772610667455-aooo5z": "left",
              "body": "left",
              "paragraph-1772528695124-y56i9f": "left"
            },
            "blockTextReflow": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": false,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockSyllableDivision": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": true,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockItalic": {
              "display": false,
              "headline": false,
              "paragraph-1772610247079-0uugg8": false,
              "paragraph-1772610667455-372iaj": false,
              "paragraph-1772610667455-aooo5z": false,
              "body": false,
              "paragraph-1772528695124-y56i9f": false
            },
            "blockRotations": {
              "display": 0,
              "headline": 0,
              "paragraph-1772610247079-0uugg8": 0,
              "paragraph-1772610667455-372iaj": 0,
              "paragraph-1772610667455-aooo5z": 0,
              "body": 0,
              "paragraph-1772528695124-y56i9f": 0
            },
            "blockModulePositions": {
              "display": {
                "column": 0,
                "row": 1,
                "baselineOffset": 0
              },
              "headline": {
                "column": 0,
                "row": 0,
                "baselineOffset": 0
              },
              "paragraph-1772610247079-0uugg8": {
                "column": 2,
                "row": 0,
                "baselineOffset": 0
              },
              "paragraph-1772610667455-372iaj": {
                "column": 1,
                "row": 0,
                "baselineOffset": 0
              },
              "paragraph-1772610667455-aooo5z": {
                "column": 3,
                "row": 0,
                "baselineOffset": 0
              },
              "body": {
                "column": 3,
                "row": 3,
                "baselineOffset": 0
              },
              "paragraph-1772528695124-y56i9f": {
                "column": 0,
                "row": 3,
                "baselineOffset": 0
              }
            },
            "blockCustomSizes": {
              "display": 106
            },
            "blockCustomLeadings": {
              "display": 90
            },
            "blockTextColors": {},
            "layerOrder": [
              "body",
              "paragraph-1772528695124-y56i9f",
              "display",
              "paragraph-1772610667455-aooo5z",
              "paragraph-1772610247079-0uugg8",
              "paragraph-1772610667455-372iaj",
              "headline"
            ],
            "imageOrder": [],
            "imageModulePositions": {},
            "imageColumnSpans": {},
            "imageRowSpans": {},
            "imageColors": {},
            "imageOpacities": {}
          }
        }
      ]
    },
  },
] as const
